version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: '⬆️ deps:'
    open-pull-requests-limit: 2
    rebase-strategy: auto
  - package-ecosystem: 'gitsubmodule'
    directory: '/'
    schedule:
      interval: 'monthly'
    commit-message:
      prefix: '⬆️ subs:'
    rebase-strategy: auto
